language: ruby
sudo: false
rvm:
  - 2.2.4
  - 2.3.0
env:
  - DB=postgresql
install: bundle install
script:
  - bin/rails db:migrate RAILS_ENV=test --trace
before_script:
  - psql -c 'create database demoapp_test' -U postgres
